substitutions:
  name: nodemcu
  friendly_name: Nodemcu
esphome:
  name: $name
  comment: Nodemcu8266
  name_add_mac_suffix: true
  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: esphomeBlack.nodemcu
    version: "1.0"
esp8266:
  board: nodemcuv2
logger:

# API is a requirement of the dashboard import.
api:

# OTA is required for Over-the-Air updating
ota:
  password: "esphome"

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: https://github.com/biloba2002/esphome-template/blob/main/nodemcu8266.yaml@main


wifi:
  # Set up a wifi access point
  ap:
    ssid: "Sonoff-Basic"
    password: "esphome"

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:

# Sets up the improv via serial client for Wi-Fi provisioning
improv_serial:

web_server:
  port: 80

status_led:
  pin: GPIO2
